"""full schema 44 tables

Revision ID: 0003_full_schema
Revises: 0002_must_change_password
Create Date: 2026-07-29 15:36:32.662911
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003_full_schema'
down_revision = '0002_must_change_password'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### extensions ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')

    # ### create new enum types (identity already owns user_role, actor_type) ###
    bind = op.get_bind()
    postgresql.ENUM("draft", "published", "reserved", "sold", "withdrawn", name="piece_status").create(bind, checkfirst=True)
    postgresql.ENUM("new", "very_good", "good", name="piece_condition").create(bind, checkfirst=True)
    postgresql.ENUM("direct_buy", "consignment", name="acquisition_type").create(bind, checkfirst=True)
    postgresql.ENUM("image", "video", name="media_type").create(bind, checkfirst=True)
    postgresql.ENUM("pending", "paid", "preparing", "ready", "delivering", "completed", "cancelled", "quote_required", name="order_status").create(bind, checkfirst=True)
    postgresql.ENUM("initiated", "pending", "succeeded", "failed", "refunded", "partially_refunded", name="payment_status").create(bind, checkfirst=True)
    postgresql.ENUM("percentage", "fixed", name="privilege_type").create(bind, checkfirst=True)
    postgresql.ENUM("pending", "approved", "rejected", "suspended", name="sourcer_status").create(bind, checkfirst=True)
    postgresql.ENUM("direct_sale", "consignment", name="collaboration_type").create(bind, checkfirst=True)
    postgresql.ENUM("submitted", "in_review", "accepted", "refused", "catalogued", name="submission_status").create(bind, checkfirst=True)
    postgresql.ENUM("pending", "approved", "paid", "failed", name="payout_status").create(bind, checkfirst=True)
    postgresql.ENUM("requested", "returned", "settled", name="entrust_status").create(bind, checkfirst=True)
    postgresql.ENUM("drop_off", "pickup", name="collection_method").create(bind, checkfirst=True)
    postgresql.ENUM("assigned", "picked_up", "in_transit", "delivered", "failed", name="delivery_status").create(bind, checkfirst=True)
    postgresql.ENUM("city", "region", name="delivery_scope").create(bind, checkfirst=True)
    postgresql.ENUM("piece_of_the_week", "favourite", "hero", name="featured_slot_type").create(bind, checkfirst=True)
    postgresql.ENUM("requested", "approved", "rejected", "resolved", name="return_status").create(bind, checkfirst=True)
    postgresql.ENUM("whatsapp", "email", "sms", "push", name="notification_channel").create(bind, checkfirst=True)
    postgresql.ENUM("queued", "sent", "delivered", "read", "failed", name="notification_status").create(bind, checkfirst=True)

    op.create_table('courier',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('notification_template',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('channel', postgresql.ENUM('whatsapp', 'email', 'sms', 'push', name='notification_channel', create_type=False), nullable=False),
    sa.Column('locale', sa.String(length=5), server_default=sa.text("'fr'"), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'channel', 'locale', name='uq_template_code_channel_locale')
    )
    op.create_table('payment_provider',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('region',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sponsor',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universe',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('division',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_region_id'), 'division', ['region_id'], unique=False)
    op.create_table('fixed_rate_city',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_fixed_rate_city_region_id'), 'fixed_rate_city', ['region_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=32), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('channel', postgresql.ENUM('whatsapp', 'email', 'sms', 'push', name='notification_channel', create_type=False), nullable=False),
    sa.Column('template_code', sa.String(length=60), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('queued', 'sent', 'delivered', 'read', 'failed', name='notification_status', create_type=False), server_default='queued', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_recipient_user_id'), 'notification', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notification_status'), 'notification', ['status'], unique=False)
    op.create_table('privilege_code',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('type', postgresql.ENUM('percentage', 'fixed', name='privilege_type', create_type=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('publication_batch',
    sa.Column('label', sa.String(length=140), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourcer_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', 'suspended', name='sourcer_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('collaboration_type', postgresql.ENUM('direct_sale', 'consignment', name='collaboration_type', create_type=False), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_method', sa.String(length=40), nullable=True),
    sa.Column('payout_phone', sa.String(length=32), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_sourcer_profile_status'), 'sourcer_profile', ['status'], unique=False)
    op.create_table('delivery_rate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scope', postgresql.ENUM('city', 'region', name='delivery_scope', create_type=False), nullable=False),
    sa.Column('city_id', sa.SmallInteger(), nullable=True),
    sa.Column('region_id', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'XAF'"), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['fixed_rate_city.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_rate_city_id'), 'delivery_rate', ['city_id'], unique=False)
    op.create_index(op.f('ix_delivery_rate_region_id'), 'delivery_rate', ['region_id'], unique=False)
    op.create_table('neighbourhood',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['fixed_rate_city.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighbourhood_city_id'), 'neighbourhood', ['city_id'], unique=False)
    op.create_table('payout',
    sa.Column('sourcer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'XAF'"), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'paid', 'failed', name='payout_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sourcer_id'], ['sourcer_profile.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_sourcer_id'), 'payout', ['sourcer_id'], unique=False)
    op.create_index(op.f('ix_payout_status'), 'payout', ['status'], unique=False)
    op.create_table('piece',
    sa.Column('sku', postgresql.CITEXT(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('house_id', sa.UUID(), nullable=True),
    sa.Column('universe_id', sa.UUID(), nullable=True),
    sa.Column('size_label', sa.String(length=32), nullable=True),
    sa.Column('condition', postgresql.ENUM('new', 'very_good', 'good', name='piece_condition', create_type=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'XAF'"), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'published', 'reserved', 'sold', 'withdrawn', name='piece_status', create_type=False), server_default='draft', nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reserved_by_order_id', sa.UUID(), nullable=True),
    sa.Column('sourcer_id', sa.UUID(), nullable=True),
    sa.Column('acquisition_type', postgresql.ENUM('direct_buy', 'consignment', name='acquisition_type', create_type=False), nullable=True),
    sa.Column('acquisition_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('consignment_share_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('publication_batch_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publication_batch_id'], ['publication_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_piece_house_id'), 'piece', ['house_id'], unique=False)
    op.create_index(op.f('ix_piece_publication_batch_id'), 'piece', ['publication_batch_id'], unique=False)
    op.create_index(op.f('ix_piece_sourcer_id'), 'piece', ['sourcer_id'], unique=False)
    op.create_index(op.f('ix_piece_status'), 'piece', ['status'], unique=False)
    op.create_index(op.f('ix_piece_universe_id'), 'piece', ['universe_id'], unique=False)
    op.create_table('purchase',
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'preparing', 'ready', 'delivering', 'completed', 'cancelled', 'quote_required', name='order_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('delivery_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_city_id', sa.Integer(), nullable=True),
    sa.Column('delivery_region_id', sa.Integer(), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'XAF'"), nullable=False),
    sa.Column('quote_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('privilege_code_id', sa.UUID(), nullable=True),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['privilege_code_id'], ['privilege_code.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_purchase_status'), 'purchase', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_user_id'), 'purchase', ['user_id'], unique=False)
    op.create_table('subdivision',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('division_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdivision_division_id'), 'subdivision', ['division_id'], unique=False)
    op.create_table('address',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('recipient_name', sa.String(length=150), nullable=False),
    sa.Column('recipient_phone', sa.String(length=32), nullable=False),
    sa.Column('city_id', sa.SmallInteger(), nullable=True),
    sa.Column('neighbourhood_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.SmallInteger(), nullable=True),
    sa.Column('division_id', sa.SmallInteger(), nullable=True),
    sa.Column('subdivision_id', sa.SmallInteger(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(city_id IS NOT NULL) <> (region_id IS NOT NULL)', name='ck_address_one_regime'),
    sa.ForeignKeyConstraint(['city_id'], ['fixed_rate_city.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivision.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_city_id'), 'address', ['city_id'], unique=False)
    op.create_index(op.f('ix_address_user_id'), 'address', ['user_id'], unique=False)
    op.create_table('delivery',
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('assigned', 'picked_up', 'in_transit', 'delivered', 'failed', name='delivery_status', create_type=False), server_default='assigned', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id')
    )
    op.create_index(op.f('ix_delivery_courier_id'), 'delivery', ['courier_id'], unique=False)
    op.create_index(op.f('ix_delivery_status'), 'delivery', ['status'], unique=False)
    op.create_table('entrust_request',
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('requested', 'returned', 'settled', name='entrust_status', create_type=False), server_default='requested', nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('handled_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrust_request_piece_id'), 'entrust_request', ['piece_id'], unique=False)
    op.create_table('featured_slot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slot', postgresql.ENUM('piece_of_the_week', 'favourite', 'hero', name='featured_slot_type', create_type=False), nullable=False),
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_featured_slot_piece_id'), 'featured_slot', ['piece_id'], unique=False)
    op.create_table('payment',
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.SmallInteger(), nullable=False),
    sa.Column('operator', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'XAF'"), nullable=False),
    sa.Column('status', postgresql.ENUM('initiated', 'pending', 'succeeded', 'failed', 'refunded', 'partially_refunded', name='payment_status', create_type=False), server_default='initiated', nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('payer_phone', sa.String(length=32), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['payment_provider.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payment_provider_reference'), 'payment', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_payment_purchase_id'), 'payment', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_table('payout_item',
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['payout.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('piece_id')
    )
    op.create_index(op.f('ix_payout_item_payout_id'), 'payout_item', ['payout_id'], unique=False)
    op.create_table('piece_media',
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('media_type', postgresql.ENUM('image', 'video', name='media_type', create_type=False), server_default='image', nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('view_label', sa.String(length=60), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piece_media_piece_id'), 'piece_media', ['piece_id'], unique=False)
    op.create_table('privilege_redemption',
    sa.Column('code_id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['privilege_code.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_id', 'purchase_id', name='uq_redemption_code_purchase')
    )
    op.create_index(op.f('ix_privilege_redemption_code_id'), 'privilege_redemption', ['code_id'], unique=False)
    op.create_table('purchase_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id', 'piece_id', name='uq_purchase_item')
    )
    op.create_index(op.f('ix_purchase_item_purchase_id'), 'purchase_item', ['purchase_id'], unique=False)
    op.create_table('purchase_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('from_status', postgresql.ENUM('pending', 'paid', 'preparing', 'ready', 'delivering', 'completed', 'cancelled', 'quote_required', name='order_status', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('pending', 'paid', 'preparing', 'ready', 'delivering', 'completed', 'cancelled', 'quote_required', name='order_status', create_type=False), nullable=False),
    sa.Column('actor_type', postgresql.ENUM('customer', 'sourcer', 'admin', 'courier', 'system', name='actor_type', create_type=False), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_status_history_purchase_id'), 'purchase_status_history', ['purchase_id'], unique=False)
    op.create_table('return_ticket',
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('requested', 'approved', 'rejected', 'resolved', name='return_status', create_type=False), server_default='requested', nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('restocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_ticket_purchase_id'), 'return_ticket', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_return_ticket_status'), 'return_ticket', ['status'], unique=False)
    op.create_table('submission',
    sa.Column('sourcer_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=80), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('size_label', sa.String(length=32), nullable=True),
    sa.Column('condition_claimed', sa.String(length=40), nullable=True),
    sa.Column('desired_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('share_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', postgresql.ENUM('submitted', 'in_review', 'accepted', 'refused', 'catalogued', name='submission_status', create_type=False), server_default='submitted', nullable=False),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('collection_method', postgresql.ENUM('drop_off', 'pickup', name='collection_method', create_type=False), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('piece_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sourcer_id'], ['sourcer_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_sourcer_id'), 'submission', ['sourcer_id'], unique=False)
    op.create_index(op.f('ix_submission_status'), 'submission', ['status'], unique=False)
    op.create_table('wishlist_item',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'piece_id')
    )
    op.create_table('courier_access_link',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_courier_access_link_delivery_id'), 'courier_access_link', ['delivery_id'], unique=False)
    op.create_table('payment_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_payment_event_payment_id'), 'payment_event', ['payment_id'], unique=False)
    op.create_table('refund',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_payment_id'), 'refund', ['payment_id'], unique=False)
    op.create_table('submission_media',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_media_submission_id'), 'submission_media', ['submission_id'], unique=False)
    op.create_table('submission_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('from_status', postgresql.ENUM('submitted', 'in_review', 'accepted', 'refused', 'catalogued', name='submission_status', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('submitted', 'in_review', 'accepted', 'refused', 'catalogued', name='submission_status', create_type=False), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_status_history_submission_id'), 'submission_status_history', ['submission_id'], unique=False)
    op.create_table('delivery_event',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('assigned', 'picked_up', 'in_transit', 'delivered', 'failed', name='delivery_status', create_type=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('link_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['courier_access_link.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_event_delivery_id'), 'delivery_event', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_event_delivery_id'), table_name='delivery_event')
    op.drop_table('delivery_event')
    op.drop_index(op.f('ix_submission_status_history_submission_id'), table_name='submission_status_history')
    op.drop_table('submission_status_history')
    op.drop_index(op.f('ix_submission_media_submission_id'), table_name='submission_media')
    op.drop_table('submission_media')
    op.drop_index(op.f('ix_refund_payment_id'), table_name='refund')
    op.drop_table('refund')
    op.drop_index(op.f('ix_payment_event_payment_id'), table_name='payment_event')
    op.drop_table('payment_event')
    op.drop_index(op.f('ix_courier_access_link_delivery_id'), table_name='courier_access_link')
    op.drop_table('courier_access_link')
    op.drop_table('wishlist_item')
    op.drop_index(op.f('ix_submission_status'), table_name='submission')
    op.drop_index(op.f('ix_submission_sourcer_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_return_ticket_status'), table_name='return_ticket')
    op.drop_index(op.f('ix_return_ticket_purchase_id'), table_name='return_ticket')
    op.drop_table('return_ticket')
    op.drop_index(op.f('ix_purchase_status_history_purchase_id'), table_name='purchase_status_history')
    op.drop_table('purchase_status_history')
    op.drop_index(op.f('ix_purchase_item_purchase_id'), table_name='purchase_item')
    op.drop_table('purchase_item')
    op.drop_index(op.f('ix_privilege_redemption_code_id'), table_name='privilege_redemption')
    op.drop_table('privilege_redemption')
    op.drop_index(op.f('ix_piece_media_piece_id'), table_name='piece_media')
    op.drop_table('piece_media')
    op.drop_index(op.f('ix_payout_item_payout_id'), table_name='payout_item')
    op.drop_table('payout_item')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_purchase_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_provider_reference'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_featured_slot_piece_id'), table_name='featured_slot')
    op.drop_table('featured_slot')
    op.drop_index(op.f('ix_entrust_request_piece_id'), table_name='entrust_request')
    op.drop_table('entrust_request')
    op.drop_index(op.f('ix_delivery_status'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_courier_id'), table_name='delivery')
    op.drop_table('delivery')
    op.drop_index(op.f('ix_address_user_id'), table_name='address')
    op.drop_index(op.f('ix_address_city_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_subdivision_division_id'), table_name='subdivision')
    op.drop_table('subdivision')
    op.drop_index(op.f('ix_purchase_user_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_status'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_piece_universe_id'), table_name='piece')
    op.drop_index(op.f('ix_piece_status'), table_name='piece')
    op.drop_index(op.f('ix_piece_sourcer_id'), table_name='piece')
    op.drop_index(op.f('ix_piece_publication_batch_id'), table_name='piece')
    op.drop_index(op.f('ix_piece_house_id'), table_name='piece')
    op.drop_table('piece')
    op.drop_index(op.f('ix_payout_status'), table_name='payout')
    op.drop_index(op.f('ix_payout_sourcer_id'), table_name='payout')
    op.drop_table('payout')
    op.drop_index(op.f('ix_neighbourhood_city_id'), table_name='neighbourhood')
    op.drop_table('neighbourhood')
    op.drop_index(op.f('ix_delivery_rate_region_id'), table_name='delivery_rate')
    op.drop_index(op.f('ix_delivery_rate_city_id'), table_name='delivery_rate')
    op.drop_table('delivery_rate')
    op.drop_index(op.f('ix_sourcer_profile_status'), table_name='sourcer_profile')
    op.drop_table('sourcer_profile')
    op.drop_table('publication_batch')
    op.drop_table('privilege_code')
    op.drop_index(op.f('ix_notification_status'), table_name='notification')
    op.drop_index(op.f('ix_notification_recipient_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_fixed_rate_city_region_id'), table_name='fixed_rate_city')
    op.drop_table('fixed_rate_city')
    op.drop_index(op.f('ix_division_region_id'), table_name='division')
    op.drop_table('division')
    op.drop_table('app_setting')
    op.drop_table('universe')
    op.drop_table('sponsor')
    op.drop_table('region')
    op.drop_table('payment_provider')
    op.drop_table('notification_template')
    op.drop_table('house')
    op.drop_table('courier')
    # ### drop new enum types ###
    bind = op.get_bind()
    postgresql.ENUM(name="piece_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="piece_condition").drop(bind, checkfirst=True)
    postgresql.ENUM(name="acquisition_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="media_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="order_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="payment_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="privilege_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="sourcer_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="collaboration_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="submission_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="payout_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="entrust_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="collection_method").drop(bind, checkfirst=True)
    postgresql.ENUM(name="delivery_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="delivery_scope").drop(bind, checkfirst=True)
    postgresql.ENUM(name="featured_slot_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="return_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="notification_channel").drop(bind, checkfirst=True)
    postgresql.ENUM(name="notification_status").drop(bind, checkfirst=True)
    # ### end Alembic commands ###

