"""add users avatar_url and avatar_key

Revision ID: 70f527f7cf4c
Revises: 0006_password_reset_code
Create Date: 2026-08-26 05:13:27.263354
"""
from alembic import op
import sqlalchemy as sa


revision = '0007_add_avatar_columns'
down_revision = '0006_password_reset_code'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_featured_slot_piece_id'), table_name='featured_slot')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('avatar_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_key')
    op.drop_column('users', 'avatar_url')
    op.create_index(op.f('ix_featured_slot_piece_id'), 'featured_slot', ['piece_id'], unique=False)
    # ### end Alembic commands ###
